global:
  resolve_timeout: 5m

route:
  receiver: discord-webhook
  group_by:
    - alertname
    - severity
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 2h

receivers:
  - name: discord-webhook
    webhook_configs:
      - url: http://alert-dispatcher:9094/alertmanager
        send_resolved: true
